- name: Update system using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['openssh-server', 'make', 'git', 'vim', 'python', 'python3', 'python3-pip', 'curl', 'net-tools']
  tags: core-tools

- name: Install Docker and Docker tools
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['docker.io', 'docker-compose']
  tags: docker

- name: Configure and start docker
  service:
    name: docker
    state: started
    enabled: true
  tags: docker

- name: Enable current user to use docker  
  user:
    name: vagrant
    groups: docker
    append: yes
  tags: docker
